######################################################################
##
## Filename: test1.udo
## Created on: Thu Sep 27 15:56:22 中国标准时间 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
